import { existsSync, watch, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import openapiTS, { astToString } from 'openapi-typescript';
import ts from 'typescript';

const specPath = fileURLToPath(
  new URL('../../api-spec/src/openapi.yaml', import.meta.url),
);
const outputPath = fileURLToPath(
  new URL('../src/schema.d.ts', import.meta.url),
);

const watchMode =
  process.argv.includes('--watch') || process.argv.includes('-w');

let pending = false;
let running = false;

async function generate() {
  if (running) {
    pending = true;
    return;
  }
  if (!existsSync(specPath)) {
    if (!watchMode) {
      throw new Error(`OpenAPI spec not found at ${specPath}`);
    }
    return;
  }
  running = true;
  try {
    console.log('[api-client] regenerating src/schema.d.ts');
    const ast = await openapiTS(pathToFileURL(specPath), {
      // Map `type: string, format: binary` (octet-stream bodies/responses)
      // to `Uint8Array` so the generated client can hand binary endpoints
      // through `openapi-fetch`'s normal `body`/response type system instead
      // of casting through `string`.
      transform(schemaObject) {
        if (
          'type' in schemaObject &&
          schemaObject.type === 'string' &&
          schemaObject.format === 'binary'
        ) {
          return ts.factory.createTypeReferenceNode('Uint8Array');
        }
        return undefined;
      },
    });
    const banner = [
      '/**',
      ' * This file was auto-generated by openapi-typescript.',
      ' * Do not make direct changes to the file.',
      ' */',
      '',
      '',
    ].join('\n');
    writeFileSync(outputPath, banner + astToString(ast));
    console.log(`[api-client] wrote ${outputPath}`);
  } catch (err) {
    if (!watchMode) throw err;
    console.error('[api-client] failed to regenerate schema:', err);
  } finally {
    running = false;
    if (pending) {
      pending = false;
      generate();
    }
  }
}

await generate();

if (!watchMode) {
  process.exit(0);
}

let debounce: NodeJS.Timeout | undefined;
const onChange = () => {
  clearTimeout(debounce);
  debounce = setTimeout(generate, 100);
};

if (existsSync(specPath)) {
  watch(specPath, onChange);
} else {
  // Spec not generated yet — wait for it to appear in the directory.
  const dirWatcher = watch(path.dirname(specPath), (_event, filename) => {
    if (filename === path.basename(specPath)) {
      dirWatcher.close();
      watch(specPath, onChange);
      onChange();
    }
  });
}

console.log(`[api-client] watching ${specPath}`);
