packages:
  - packages/*

catalog:
  '@andrewbranch/untar.js': 1.0.3
  '@biomejs/biome': 2.1.2
  '@codemirror/autocomplete': 6.18.6
  '@codemirror/commands': 6.8.1
  '@codemirror/lang-css': 6.3.1
  '@codemirror/language': 6.11.0
  '@codemirror/state': 6.5.2
  '@codemirror/view': 6.37.1
  '@tailwindcss/vite': 4.0.12
  '@tanstack/react-router': 1.97.1
  '@tanstack/router-devtools': 1.97.1
  '@tanstack/router-plugin': 1.97.1
  '@tiptap/core': 2.14.0
  '@tiptap/extension-blockquote': 2.14.0
  '@tiptap/extension-bold': 2.14.0
  '@tiptap/extension-bullet-list': 2.14.0
  '@tiptap/extension-code': 2.14.0
  '@tiptap/extension-code-block': 2.14.0
  '@tiptap/extension-collaboration': 2.14.0
  '@tiptap/extension-document': 2.14.0
  '@tiptap/extension-dropcursor': 2.14.0
  '@tiptap/extension-gapcursor': 2.14.0
  '@tiptap/extension-hard-break': 2.14.0
  '@tiptap/extension-heading': 2.14.0
  '@tiptap/extension-history': 2.14.0
  '@tiptap/extension-horizontal-rule': 2.14.0
  '@tiptap/extension-italic': 2.14.0
  '@tiptap/extension-list-item': 2.14.0
  '@tiptap/extension-ordered-list': 2.14.0
  '@tiptap/extension-paragraph': 2.14.0
  '@tiptap/extension-placeholder': 2.14.0
  '@tiptap/extension-strike': 2.14.0
  '@tiptap/extension-text': 2.14.0
  '@tiptap/extension-text-style': 2.14.0
  '@tiptap/pm': 2.14.0
  '@tiptap/react': 2.14.0
  '@types/node': 22.10.7
  '@types/react': 19.1.1
  '@types/react-dom': 19.1.2
  '@types/semver': 7.5.8
  '@vitejs/plugin-react-swc': 3.7.2
  '@vitest/coverage-v8': 3.2.3
  '@vitest/ui': 3.2.3
  '@vivliostyle/cli': 9.2.0
  '@vivliostyle/theme-base': 2.0.0
  comlink: 4.4.2
  husky: 9.1.7
  fflate: 0.8.2
  lightningcss-wasm: 1.30.1
  lint-staged: 15.4.1
  magic-string: 0.30.17
  memfs: 4.17.2
  nanoid: 5.1.5
  nanoid-dictionary: 5.0.0
  outvariant: 1.4.3
  pathe: 2.0.3
  pnpm: 10.12.1
  react: 19.1.0
  react-dom: 19.1.0
  react-shadow: 20.6.0
  react-use: 17.6.0
  semver: 7.7.1
  tailwindcss: 4.0.12
  tailwindcss-animate: 1.0.7
  tsx: 4.19.3
  turbo: 2.3.3
  typescript: 5.7.3
  valtio: 2.1.4
  vite: 6.2.1
  vite-plugin-pwa: 0.21.1
  vitest: 3.2.3
  y-indexeddb: 9.0.12
  y-prosemirror: 1.2.17
  yjs: 13.6.24
