import { fs, vol } from 'memfs';

// Rolldown places @vivliostyle/cli's chunks ~400K lines before volume.ts in the
// bundle. Those chunks run IIFEs that call readFileSync('/workdir/node_modules/
// @vivliostyle/cli/package.json') and '@vivliostyle/viewer/package.json' at
// module-init time. Pre-populate the virtual filesystem here — fs.ts is placed
// early (before @vivliostyle/cli) because every Node built-in that uses the fs
// depends on it transitively.
vol.fromJSON(__volume__);

export default fs;

export const {
  constants,
  Stats,
  Dirent,
  accessSync,
  appendFileSync,
  chmodSync,
  chownSync,
  closeSync,
  copyFileSync,
  existsSync,
  fchmodSync,
  fchownSync,
  fdatasyncSync,
  fstatSync,
  fsyncSync,
  ftruncateSync,
  futimesSync,
  lchmodSync,
  lchownSync,
  linkSync,
  lstatSync,
  mkdirSync,
  mkdtempSync,
  openSync,
  readdirSync,
  readFileSync,
  readlinkSync,
  readSync,
  readvSync,
  realpathSync,
  renameSync,
  rmdirSync,
  rmSync,
  statSync,
  symlinkSync,
  truncateSync,
  unlinkSync,
  utimesSync,
  lutimesSync,
  writeFileSync,
  writeSync,
  writevSync,
  access,
  appendFile,
  chmod,
  chown,
  close,
  copyFile,
  createReadStream,
  createWriteStream,
  exists,
  fchmod,
  fchown,
  fdatasync,
  fstat,
  fsync,
  ftruncate,
  futimes,
  lchmod,
  lchown,
  link,
  lstat,
  mkdir,
  mkdtemp,
  open,
  read,
  readv,
  readdir,
  readFile,
  readlink,
  realpath,
  rename,
  rm,
  rmdir,
  stat,
  symlink,
  truncate,
  unlink,
  unwatchFile,
  utimes,
  lutimes,
  watch,
  watchFile,
  write,
  writev,
  writeFile,
  StatWatcher,
  FSWatcher,
  WriteStream,
  ReadStream,
  promises,
  _toUnixTimestamp,
} = fs;

realpath.native = realpath;
realpathSync.native = realpathSync;
