/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainLayoutRouteImport } from './routes/(main)/_layout'
import { Route as DebugAstViewerIndexRouteImport } from './routes/debug/ast-viewer/index'
import { Route as mainLayoutIndexRouteImport } from './routes/(main)/_layout/index'
import { Route as mainLayoutThemeRouteImport } from './routes/(main)/_layout/theme'
import { Route as mainLayoutPreviewRouteImport } from './routes/(main)/_layout/preview'
import { Route as mainLayoutNewProjectRouteImport } from './routes/(main)/_layout/new-project'
import { Route as mainLayoutMediaRouteImport } from './routes/(main)/_layout/media'
import { Route as mainLayoutBibliographyRouteImport } from './routes/(main)/_layout/bibliography'
import { Route as mainLayoutEditSplatRouteImport } from './routes/(main)/_layout/edit/$'

const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAstViewerIndexRoute = DebugAstViewerIndexRouteImport.update({
  id: '/debug/ast-viewer/',
  path: '/debug/ast-viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutIndexRoute = mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutThemeRoute = mainLayoutThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutPreviewRoute = mainLayoutPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutNewProjectRoute = mainLayoutNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutMediaRoute = mainLayoutMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutBibliographyRoute = mainLayoutBibliographyRouteImport.update({
  id: '/bibliography',
  path: '/bibliography',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutEditSplatRoute = mainLayoutEditSplatRouteImport.update({
  id: '/edit/$',
  path: '/edit/$',
  getParentRoute: () => mainLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/bibliography': typeof mainLayoutBibliographyRoute
  '/media': typeof mainLayoutMediaRoute
  '/new-project': typeof mainLayoutNewProjectRoute
  '/preview': typeof mainLayoutPreviewRoute
  '/theme': typeof mainLayoutThemeRoute
  '/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer/': typeof DebugAstViewerIndexRoute
  '/edit/$': typeof mainLayoutEditSplatRoute
}
export interface FileRoutesByTo {
  '/bibliography': typeof mainLayoutBibliographyRoute
  '/media': typeof mainLayoutMediaRoute
  '/new-project': typeof mainLayoutNewProjectRoute
  '/preview': typeof mainLayoutPreviewRoute
  '/theme': typeof mainLayoutThemeRoute
  '/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer': typeof DebugAstViewerIndexRoute
  '/edit/$': typeof mainLayoutEditSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_layout': typeof mainLayoutRouteWithChildren
  '/(main)/_layout/bibliography': typeof mainLayoutBibliographyRoute
  '/(main)/_layout/media': typeof mainLayoutMediaRoute
  '/(main)/_layout/new-project': typeof mainLayoutNewProjectRoute
  '/(main)/_layout/preview': typeof mainLayoutPreviewRoute
  '/(main)/_layout/theme': typeof mainLayoutThemeRoute
  '/(main)/_layout/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer/': typeof DebugAstViewerIndexRoute
  '/(main)/_layout/edit/$': typeof mainLayoutEditSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/bibliography'
    | '/media'
    | '/new-project'
    | '/preview'
    | '/theme'
    | '/'
    | '/debug/ast-viewer/'
    | '/edit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/bibliography'
    | '/media'
    | '/new-project'
    | '/preview'
    | '/theme'
    | '/'
    | '/debug/ast-viewer'
    | '/edit/$'
  id:
    | '__root__'
    | '/(main)/_layout'
    | '/(main)/_layout/bibliography'
    | '/(main)/_layout/media'
    | '/(main)/_layout/new-project'
    | '/(main)/_layout/preview'
    | '/(main)/_layout/theme'
    | '/(main)/_layout/'
    | '/debug/ast-viewer/'
    | '/(main)/_layout/edit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
  DebugAstViewerIndexRoute: typeof DebugAstViewerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)/_layout': {
      id: '/(main)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/ast-viewer/': {
      id: '/debug/ast-viewer/'
      path: '/debug/ast-viewer'
      fullPath: '/debug/ast-viewer/'
      preLoaderRoute: typeof DebugAstViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout/': {
      id: '/(main)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainLayoutIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/theme': {
      id: '/(main)/_layout/theme'
      path: '/theme'
      fullPath: '/theme'
      preLoaderRoute: typeof mainLayoutThemeRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/preview': {
      id: '/(main)/_layout/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof mainLayoutPreviewRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/new-project': {
      id: '/(main)/_layout/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof mainLayoutNewProjectRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/media': {
      id: '/(main)/_layout/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof mainLayoutMediaRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/bibliography': {
      id: '/(main)/_layout/bibliography'
      path: '/bibliography'
      fullPath: '/bibliography'
      preLoaderRoute: typeof mainLayoutBibliographyRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/edit/$': {
      id: '/(main)/_layout/edit/$'
      path: '/edit/$'
      fullPath: '/edit/$'
      preLoaderRoute: typeof mainLayoutEditSplatRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface mainLayoutRouteChildren {
  mainLayoutBibliographyRoute: typeof mainLayoutBibliographyRoute
  mainLayoutMediaRoute: typeof mainLayoutMediaRoute
  mainLayoutNewProjectRoute: typeof mainLayoutNewProjectRoute
  mainLayoutPreviewRoute: typeof mainLayoutPreviewRoute
  mainLayoutThemeRoute: typeof mainLayoutThemeRoute
  mainLayoutIndexRoute: typeof mainLayoutIndexRoute
  mainLayoutEditSplatRoute: typeof mainLayoutEditSplatRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  mainLayoutBibliographyRoute: mainLayoutBibliographyRoute,
  mainLayoutMediaRoute: mainLayoutMediaRoute,
  mainLayoutNewProjectRoute: mainLayoutNewProjectRoute,
  mainLayoutPreviewRoute: mainLayoutPreviewRoute,
  mainLayoutThemeRoute: mainLayoutThemeRoute,
  mainLayoutIndexRoute: mainLayoutIndexRoute,
  mainLayoutEditSplatRoute: mainLayoutEditSplatRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainLayoutRoute: mainLayoutRouteWithChildren,
  DebugAstViewerIndexRoute: DebugAstViewerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
