/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugIndexRouteImport } from './routes/debug/index'
import { Route as mainLayoutRouteImport } from './routes/(main)/_layout'
import { Route as DebugIndexeddbPersistenceIndexRouteImport } from './routes/debug/indexeddb-persistence/index'
import { Route as DebugAstViewerIndexRouteImport } from './routes/debug/ast-viewer/index'
import { Route as mainLayoutIndexRouteImport } from './routes/(main)/_layout/index'
import { Route as mainLayoutNewProjectRouteImport } from './routes/(main)/_layout/new-project'
import { Route as mainLayoutProjectsProjectIdIndexRouteImport } from './routes/(main)/_layout/projects/$projectId/index'
import { Route as mainLayoutProjectsProjectIdThemeRouteImport } from './routes/(main)/_layout/projects/$projectId/theme'
import { Route as mainLayoutProjectsProjectIdPreviewRouteImport } from './routes/(main)/_layout/projects/$projectId/preview'
import { Route as mainLayoutProjectsProjectIdMediaRouteImport } from './routes/(main)/_layout/projects/$projectId/media'
import { Route as mainLayoutProjectsProjectIdBibliographyRouteImport } from './routes/(main)/_layout/projects/$projectId/bibliography'
import { Route as mainLayoutProjectsProjectIdEditSplatRouteImport } from './routes/(main)/_layout/projects/$projectId/edit/$'

const DebugIndexRoute = DebugIndexRouteImport.update({
  id: '/debug/',
  path: '/debug/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutRoute = mainLayoutRouteImport.update({
  id: '/(main)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugIndexeddbPersistenceIndexRoute =
  DebugIndexeddbPersistenceIndexRouteImport.update({
    id: '/debug/indexeddb-persistence/',
    path: '/debug/indexeddb-persistence/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DebugAstViewerIndexRoute = DebugAstViewerIndexRouteImport.update({
  id: '/debug/ast-viewer/',
  path: '/debug/ast-viewer/',
  getParentRoute: () => rootRouteImport,
} as any)
const mainLayoutIndexRoute = mainLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutNewProjectRoute = mainLayoutNewProjectRouteImport.update({
  id: '/new-project',
  path: '/new-project',
  getParentRoute: () => mainLayoutRoute,
} as any)
const mainLayoutProjectsProjectIdIndexRoute =
  mainLayoutProjectsProjectIdIndexRouteImport.update({
    id: '/projects/$projectId/',
    path: '/projects/$projectId/',
    getParentRoute: () => mainLayoutRoute,
  } as any)
const mainLayoutProjectsProjectIdThemeRoute =
  mainLayoutProjectsProjectIdThemeRouteImport.update({
    id: '/projects/$projectId/theme',
    path: '/projects/$projectId/theme',
    getParentRoute: () => mainLayoutRoute,
  } as any)
const mainLayoutProjectsProjectIdPreviewRoute =
  mainLayoutProjectsProjectIdPreviewRouteImport.update({
    id: '/projects/$projectId/preview',
    path: '/projects/$projectId/preview',
    getParentRoute: () => mainLayoutRoute,
  } as any)
const mainLayoutProjectsProjectIdMediaRoute =
  mainLayoutProjectsProjectIdMediaRouteImport.update({
    id: '/projects/$projectId/media',
    path: '/projects/$projectId/media',
    getParentRoute: () => mainLayoutRoute,
  } as any)
const mainLayoutProjectsProjectIdBibliographyRoute =
  mainLayoutProjectsProjectIdBibliographyRouteImport.update({
    id: '/projects/$projectId/bibliography',
    path: '/projects/$projectId/bibliography',
    getParentRoute: () => mainLayoutRoute,
  } as any)
const mainLayoutProjectsProjectIdEditSplatRoute =
  mainLayoutProjectsProjectIdEditSplatRouteImport.update({
    id: '/projects/$projectId/edit/$',
    path: '/projects/$projectId/edit/$',
    getParentRoute: () => mainLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/debug/': typeof DebugIndexRoute
  '/new-project': typeof mainLayoutNewProjectRoute
  '/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer/': typeof DebugAstViewerIndexRoute
  '/debug/indexeddb-persistence/': typeof DebugIndexeddbPersistenceIndexRoute
  '/projects/$projectId/bibliography': typeof mainLayoutProjectsProjectIdBibliographyRoute
  '/projects/$projectId/media': typeof mainLayoutProjectsProjectIdMediaRoute
  '/projects/$projectId/preview': typeof mainLayoutProjectsProjectIdPreviewRoute
  '/projects/$projectId/theme': typeof mainLayoutProjectsProjectIdThemeRoute
  '/projects/$projectId/': typeof mainLayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/edit/$': typeof mainLayoutProjectsProjectIdEditSplatRoute
}
export interface FileRoutesByTo {
  '/debug': typeof DebugIndexRoute
  '/new-project': typeof mainLayoutNewProjectRoute
  '/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer': typeof DebugAstViewerIndexRoute
  '/debug/indexeddb-persistence': typeof DebugIndexeddbPersistenceIndexRoute
  '/projects/$projectId/bibliography': typeof mainLayoutProjectsProjectIdBibliographyRoute
  '/projects/$projectId/media': typeof mainLayoutProjectsProjectIdMediaRoute
  '/projects/$projectId/preview': typeof mainLayoutProjectsProjectIdPreviewRoute
  '/projects/$projectId/theme': typeof mainLayoutProjectsProjectIdThemeRoute
  '/projects/$projectId': typeof mainLayoutProjectsProjectIdIndexRoute
  '/projects/$projectId/edit/$': typeof mainLayoutProjectsProjectIdEditSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)/_layout': typeof mainLayoutRouteWithChildren
  '/debug/': typeof DebugIndexRoute
  '/(main)/_layout/new-project': typeof mainLayoutNewProjectRoute
  '/(main)/_layout/': typeof mainLayoutIndexRoute
  '/debug/ast-viewer/': typeof DebugAstViewerIndexRoute
  '/debug/indexeddb-persistence/': typeof DebugIndexeddbPersistenceIndexRoute
  '/(main)/_layout/projects/$projectId/bibliography': typeof mainLayoutProjectsProjectIdBibliographyRoute
  '/(main)/_layout/projects/$projectId/media': typeof mainLayoutProjectsProjectIdMediaRoute
  '/(main)/_layout/projects/$projectId/preview': typeof mainLayoutProjectsProjectIdPreviewRoute
  '/(main)/_layout/projects/$projectId/theme': typeof mainLayoutProjectsProjectIdThemeRoute
  '/(main)/_layout/projects/$projectId/': typeof mainLayoutProjectsProjectIdIndexRoute
  '/(main)/_layout/projects/$projectId/edit/$': typeof mainLayoutProjectsProjectIdEditSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/debug/'
    | '/new-project'
    | '/'
    | '/debug/ast-viewer/'
    | '/debug/indexeddb-persistence/'
    | '/projects/$projectId/bibliography'
    | '/projects/$projectId/media'
    | '/projects/$projectId/preview'
    | '/projects/$projectId/theme'
    | '/projects/$projectId/'
    | '/projects/$projectId/edit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/debug'
    | '/new-project'
    | '/'
    | '/debug/ast-viewer'
    | '/debug/indexeddb-persistence'
    | '/projects/$projectId/bibliography'
    | '/projects/$projectId/media'
    | '/projects/$projectId/preview'
    | '/projects/$projectId/theme'
    | '/projects/$projectId'
    | '/projects/$projectId/edit/$'
  id:
    | '__root__'
    | '/(main)/_layout'
    | '/debug/'
    | '/(main)/_layout/new-project'
    | '/(main)/_layout/'
    | '/debug/ast-viewer/'
    | '/debug/indexeddb-persistence/'
    | '/(main)/_layout/projects/$projectId/bibliography'
    | '/(main)/_layout/projects/$projectId/media'
    | '/(main)/_layout/projects/$projectId/preview'
    | '/(main)/_layout/projects/$projectId/theme'
    | '/(main)/_layout/projects/$projectId/'
    | '/(main)/_layout/projects/$projectId/edit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainLayoutRoute: typeof mainLayoutRouteWithChildren
  DebugIndexRoute: typeof DebugIndexRoute
  DebugAstViewerIndexRoute: typeof DebugAstViewerIndexRoute
  DebugIndexeddbPersistenceIndexRoute: typeof DebugIndexeddbPersistenceIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug/': {
      id: '/debug/'
      path: '/debug'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout': {
      id: '/(main)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/indexeddb-persistence/': {
      id: '/debug/indexeddb-persistence/'
      path: '/debug/indexeddb-persistence'
      fullPath: '/debug/indexeddb-persistence/'
      preLoaderRoute: typeof DebugIndexeddbPersistenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/ast-viewer/': {
      id: '/debug/ast-viewer/'
      path: '/debug/ast-viewer'
      fullPath: '/debug/ast-viewer/'
      preLoaderRoute: typeof DebugAstViewerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/_layout/': {
      id: '/(main)/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainLayoutIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/new-project': {
      id: '/(main)/_layout/new-project'
      path: '/new-project'
      fullPath: '/new-project'
      preLoaderRoute: typeof mainLayoutNewProjectRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/': {
      id: '/(main)/_layout/projects/$projectId/'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdIndexRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/theme': {
      id: '/(main)/_layout/projects/$projectId/theme'
      path: '/projects/$projectId/theme'
      fullPath: '/projects/$projectId/theme'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdThemeRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/preview': {
      id: '/(main)/_layout/projects/$projectId/preview'
      path: '/projects/$projectId/preview'
      fullPath: '/projects/$projectId/preview'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdPreviewRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/media': {
      id: '/(main)/_layout/projects/$projectId/media'
      path: '/projects/$projectId/media'
      fullPath: '/projects/$projectId/media'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdMediaRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/bibliography': {
      id: '/(main)/_layout/projects/$projectId/bibliography'
      path: '/projects/$projectId/bibliography'
      fullPath: '/projects/$projectId/bibliography'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdBibliographyRouteImport
      parentRoute: typeof mainLayoutRoute
    }
    '/(main)/_layout/projects/$projectId/edit/$': {
      id: '/(main)/_layout/projects/$projectId/edit/$'
      path: '/projects/$projectId/edit/$'
      fullPath: '/projects/$projectId/edit/$'
      preLoaderRoute: typeof mainLayoutProjectsProjectIdEditSplatRouteImport
      parentRoute: typeof mainLayoutRoute
    }
  }
}

interface mainLayoutRouteChildren {
  mainLayoutNewProjectRoute: typeof mainLayoutNewProjectRoute
  mainLayoutIndexRoute: typeof mainLayoutIndexRoute
  mainLayoutProjectsProjectIdBibliographyRoute: typeof mainLayoutProjectsProjectIdBibliographyRoute
  mainLayoutProjectsProjectIdMediaRoute: typeof mainLayoutProjectsProjectIdMediaRoute
  mainLayoutProjectsProjectIdPreviewRoute: typeof mainLayoutProjectsProjectIdPreviewRoute
  mainLayoutProjectsProjectIdThemeRoute: typeof mainLayoutProjectsProjectIdThemeRoute
  mainLayoutProjectsProjectIdIndexRoute: typeof mainLayoutProjectsProjectIdIndexRoute
  mainLayoutProjectsProjectIdEditSplatRoute: typeof mainLayoutProjectsProjectIdEditSplatRoute
}

const mainLayoutRouteChildren: mainLayoutRouteChildren = {
  mainLayoutNewProjectRoute: mainLayoutNewProjectRoute,
  mainLayoutIndexRoute: mainLayoutIndexRoute,
  mainLayoutProjectsProjectIdBibliographyRoute:
    mainLayoutProjectsProjectIdBibliographyRoute,
  mainLayoutProjectsProjectIdMediaRoute: mainLayoutProjectsProjectIdMediaRoute,
  mainLayoutProjectsProjectIdPreviewRoute:
    mainLayoutProjectsProjectIdPreviewRoute,
  mainLayoutProjectsProjectIdThemeRoute: mainLayoutProjectsProjectIdThemeRoute,
  mainLayoutProjectsProjectIdIndexRoute: mainLayoutProjectsProjectIdIndexRoute,
  mainLayoutProjectsProjectIdEditSplatRoute:
    mainLayoutProjectsProjectIdEditSplatRoute,
}

const mainLayoutRouteWithChildren = mainLayoutRoute._addFileChildren(
  mainLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainLayoutRoute: mainLayoutRouteWithChildren,
  DebugIndexRoute: DebugIndexRoute,
  DebugAstViewerIndexRoute: DebugAstViewerIndexRoute,
  DebugIndexeddbPersistenceIndexRoute: DebugIndexeddbPersistenceIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
