/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/vivliostyle-pub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Describe the server and the optional features it supports. */
        get: operations["getWellKnownVivliostylePub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user account.
         * @description Creates an account with the given username and password. Sign in via `/oauth/authorize` afterwards to obtain access tokens.
         */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in and receive an authorization code.
         * @description Verifies the username and password and returns a short-lived authorization code. Exchange it for tokens by calling `/oauth/token` with the matching PKCE verifier.
         */
        post: operations["postOauthAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange an authorization code or refresh token for an access token.
         * @description Two grant types are supported: `authorization_code` (after `/oauth/authorize`) and `refresh_token` (to rotate an existing session).
         */
        post: operations["postOauthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renew the access token using a refresh token.
         * @description Returns a new access token and rotates the refresh token. The previous refresh token is invalidated.
         */
        post: operations["postOauthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Sign out the current user.
         * @description Revokes every access and refresh token issued to the signed-in user.
         */
        delete: operations["deleteOauthSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the profile of the signed-in user. */
        get: operations["getOauthUserinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the authenticated user's projects. */
        get: operations["getProjects"];
        put?: never;
        /** Create a project. */
        post: operations["postProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get project metadata. */
        get: operations["getProjectsById"];
        /** Update project metadata. */
        put: operations["putProjectsById"];
        post?: never;
        /** Delete a project. */
        delete: operations["deleteProjectsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/sync/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Pull the latest document updates for a file.
         * @description Returns the Yjs update needed to bring the caller up to date for one file in a project. If the `sv` query parameter is supplied, only the delta missing from that state vector is returned; otherwise the full document state is returned.
         */
        get: operations["getProjectsByIdSyncByPath"];
        put?: never;
        /**
         * Push a file's local updates and pull remote updates back.
         * @description Applies the Yjs update sent in the request body to the file-scoped document, then returns the update the caller still needs to converge with the server (filtered by the `sv` state vector when supplied). Send an empty body to pull-only.
         */
        post: operations["postProjectsByIdSyncByPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List files in a project. */
        get: operations["getProjectsByIdFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read a file. */
        get: operations["getProjectsByIdFilesByPath"];
        /** Create or replace a file. */
        put: operations["putProjectsByIdFilesByPath"];
        post?: never;
        /** Delete a file. */
        delete: operations["deleteProjectsByIdFilesByPath"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/attachments/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download an attachment by its SHA-256 hash. */
        get: operations["getProjectsByIdAttachmentsBySha256"];
        /**
         * Upload an attachment.
         * @description The SHA-256 hex digest of the request body must match the `sha256` path parameter; uploads that fail this check are rejected. Uploading the same hash twice is idempotent.
         */
        put: operations["putProjectsByIdAttachmentsBySha256"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWellKnownVivliostylePub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        version: string;
                        apiVersions: string[];
                        features: {
                            sync: boolean;
                            attachments: boolean;
                            oauth: boolean;
                        };
                    };
                };
            };
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientId: string;
                    /** Format: uri */
                    redirectUri: string;
                    codeChallenge: string;
                    /**
                     * @default S256
                     * @constant
                     */
                    codeChallengeMethod?: "S256";
                    scope?: string;
                    state?: string;
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authorization code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        state?: string;
                        redirectUri: string;
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    grantType: "authorization_code";
                    code: string;
                    codeVerifier: string;
                    /** Format: uri */
                    redirectUri: string;
                    clientId: string;
                } | {
                    /** @constant */
                    grantType: "refresh_token";
                    refreshToken: string;
                    clientId: string;
                };
            };
        };
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        /** @constant */
                        tokenType: "Bearer";
                        expiresIn: number;
                        refreshToken: string;
                        scope?: string;
                    };
                };
            };
            /** @description Invalid grant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                    clientId: string;
                };
            };
        };
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        /** @constant */
                        tokenType: "Bearer";
                        expiresIn: number;
                        refreshToken: string;
                        scope?: string;
                    };
                };
            };
            /** @description Invalid refresh token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteOauthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getOauthUserinfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: {
                            id: string;
                            title?: string;
                            author?: string;
                            language?: string;
                            createdAt: number;
                            updatedAt: number;
                        }[];
                    };
                };
            };
        };
    };
    postProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
        };
    };
    getProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Merged Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: {
                            path: string;
                            size: number;
                            contentType: string;
                            updatedAt: number;
                        }[];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sha256: string;
                        size: number;
                    };
                };
            };
            /** @description Hash mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
}
