/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/vivliostyle-pub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Returns the server name, supported API versions, and which optional features it implements.
         */
        get: operations["getWellKnownVivliostylePub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Creates a new user account; sign in via `/auth/sign-in` afterwards, then `/auth/oauth2/authorize` → `/auth/oauth2/token` to obtain access tokens.
         */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sign in
         * @description Verifies the username and password and starts a session, returning the session token to authorize `/auth/oauth2/authorize`.
         */
        post: operations["postAuthSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Authorize
         * @description Issues a short-lived authorization code for the session given in the `Authorization: Bearer <session token>` header (from `/auth/sign-in`), returning the redirect URI carrying the code to exchange via `/auth/oauth2/token` with the matching PKCE verifier.
         */
        get: operations["getAuthOauth2Authorize"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token
         * @description Exchanges an authorization code (after `/auth/oauth2/authorize`) or a refresh token for an access token. The refresh token is rotated, invalidating the previous one.
         */
        post: operations["postAuthOauth2Token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke
         * @description Revokes a token (RFC 7009). Revoking a refresh token also drops the access tokens of the same grant. Always responds 200, even for an unknown or already-revoked token.
         */
        post: operations["postAuthOauth2Revoke"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Logout
         * @description Revokes every access and refresh token issued to the signed-in user.
         */
        delete: operations["deleteAuthOauth2Session"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oauth2/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * User info
         * @description Returns the signed-in user's OpenID Connect claims.
         */
        get: operations["getAuthOauth2Userinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns all projects owned by the authenticated user.
         */
        get: operations["getProjects"];
        put?: never;
        /**
         * Create project
         * @description Creates a new project owned by the authenticated user.
         */
        post: operations["postProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Returns the project's metadata.
         */
        get: operations["getProjectsById"];
        /**
         * Update project
         * @description Replaces the project's metadata with the request body.
         */
        put: operations["putProjectsById"];
        post?: never;
        /**
         * Delete project
         * @description Removes the project along with all of its files and document state.
         */
        delete: operations["deleteProjectsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/sync/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync pull
         * @description Returns the Yjs update needed to bring the caller's copy of one file up to date — limited to the delta missing from the `sv` state vector when supplied, or the full state otherwise.
         */
        get: operations["getProjectsByIdSyncByPath"];
        put?: never;
        /**
         * Sync push
         * @description Applies the Yjs update in the request body and returns the diff the caller is still missing — filtered by the `sv` state vector when supplied, with an empty body acting as pull-only.
         */
        post: operations["postProjectsByIdSyncByPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files
         * @description Returns every file currently stored in the project.
         */
        get: operations["getProjectsByIdFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read file
         * @description Returns the file's raw bytes.
         */
        get: operations["getProjectsByIdFilesByPath"];
        /**
         * Write file
         * @description Creates or replaces the file at the given path.
         */
        put: operations["putProjectsByIdFilesByPath"];
        post?: never;
        /**
         * Delete file
         * @description Removes the file and drops its associated CRDT state.
         */
        delete: operations["deleteProjectsByIdFilesByPath"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/attachments/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attachment
         * @description Returns the attachment whose SHA-256 hex digest matches the path parameter.
         */
        get: operations["getProjectsByIdAttachmentsBySha256"];
        /**
         * Put attachment
         * @description Stores the attachment keyed by its SHA-256 hex digest; the request body's digest must match the path parameter, and uploading the same hash twice is idempotent.
         */
        put: operations["putProjectsByIdAttachmentsBySha256"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWellKnownVivliostylePub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        version: string;
                        apiVersions: string[];
                        features: {
                            sync: boolean;
                            attachments: boolean;
                            oauth: boolean;
                        };
                    };
                };
            };
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postAuthSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        token: string;
                        user: {
                            id: string;
                            username: string;
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getAuthOauth2Authorize: {
        parameters: {
            query: {
                response_type?: "code";
                client_id: string;
                redirect_uri: string;
                scope?: string;
                state?: string;
                code_challenge: string;
                code_challenge_method?: "S256";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorization redirect */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        redirect: boolean;
                        url: string;
                    };
                };
            };
            /** @description Invalid session */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postAuthOauth2Token: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    /** @constant */
                    grant_type: "authorization_code";
                    code: string;
                    code_verifier: string;
                    /** Format: uri */
                    redirect_uri: string;
                    client_id: string;
                } | {
                    /** @constant */
                    grant_type: "refresh_token";
                    refresh_token: string;
                    client_id: string;
                };
            };
        };
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        access_token: string;
                        /** @constant */
                        token_type: "Bearer";
                        expires_in: number;
                        refresh_token: string;
                        scope?: string;
                    };
                };
            };
            /** @description Invalid grant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postAuthOauth2Revoke: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": {
                    token: string;
                    /** @enum {string} */
                    token_type_hint?: "access_token" | "refresh_token";
                    client_id: string;
                };
            };
        };
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteAuthOauth2Session: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getAuthOauth2Userinfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Claims */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sub: string;
                        name: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: {
                            id: string;
                            title?: string;
                            author?: string;
                            language?: string;
                            createdAt: number;
                            updatedAt: number;
                        }[];
                    };
                };
            };
        };
    };
    postProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
        };
    };
    getProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Merged Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: {
                            path: string;
                            size: number;
                            contentType: string;
                            updatedAt: number;
                        }[];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sha256: string;
                        size: number;
                    };
                };
            };
            /** @description Hash mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
}
