/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/.well-known/vivliostyle-pub": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Capabilities
         * @description Returns the server name, supported API versions, and which optional features it implements.
         */
        get: operations["getWellKnownVivliostylePub"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Creates a new user account; sign in via `/oauth/authorize` afterwards to obtain access tokens.
         */
        post: operations["postAuthRegister"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authorize
         * @description Verifies the username and password and returns a short-lived authorization code to exchange via `/oauth/token` with the matching PKCE verifier.
         */
        post: operations["postOauthAuthorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Token
         * @description Exchanges an authorization code (after `/oauth/authorize`) or a refresh token for an access token.
         */
        post: operations["postOauthToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh
         * @description Issues a new access token and rotates the refresh token, invalidating the previous one.
         */
        post: operations["postOauthRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Logout
         * @description Revokes every access and refresh token issued to the signed-in user.
         */
        delete: operations["deleteOauthSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/userinfo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get user
         * @description Returns the signed-in user's profile.
         */
        get: operations["getOauthUserinfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description Returns all projects owned by the authenticated user.
         */
        get: operations["getProjects"];
        put?: never;
        /**
         * Create project
         * @description Creates a new project owned by the authenticated user.
         */
        post: operations["postProjects"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Returns the project's metadata.
         */
        get: operations["getProjectsById"];
        /**
         * Update project
         * @description Replaces the project's metadata with the request body.
         */
        put: operations["putProjectsById"];
        post?: never;
        /**
         * Delete project
         * @description Removes the project along with all of its files and document state.
         */
        delete: operations["deleteProjectsById"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/sync/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sync pull
         * @description Returns the Yjs update needed to bring the caller's copy of one file up to date — limited to the delta missing from the `sv` state vector when supplied, or the full state otherwise.
         */
        get: operations["getProjectsByIdSyncByPath"];
        put?: never;
        /**
         * Sync push
         * @description Applies the Yjs update in the request body and returns the diff the caller is still missing — filtered by the `sv` state vector when supplied, with an empty body acting as pull-only.
         */
        post: operations["postProjectsByIdSyncByPath"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List files
         * @description Returns every file currently stored in the project.
         */
        get: operations["getProjectsByIdFiles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/files/{path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read file
         * @description Returns the file's raw bytes.
         */
        get: operations["getProjectsByIdFilesByPath"];
        /**
         * Write file
         * @description Creates or replaces the file at the given path.
         */
        put: operations["putProjectsByIdFilesByPath"];
        post?: never;
        /**
         * Delete file
         * @description Removes the file and drops its associated CRDT state.
         */
        delete: operations["deleteProjectsByIdFilesByPath"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}/attachments/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get attachment
         * @description Returns the attachment whose SHA-256 hex digest matches the path parameter.
         */
        get: operations["getProjectsByIdAttachmentsBySha256"];
        /**
         * Put attachment
         * @description Stores the attachment keyed by its SHA-256 hex digest; the request body's digest must match the path parameter, and uploading the same hash twice is idempotent.
         */
        put: operations["putProjectsByIdAttachmentsBySha256"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWellKnownVivliostylePub: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capabilities */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        name: string;
                        version: string;
                        apiVersions: string[];
                        features: {
                            sync: boolean;
                            attachments: boolean;
                            oauth: boolean;
                        };
                    };
                };
            };
        };
    };
    postAuthRegister: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthAuthorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    clientId: string;
                    /** Format: uri */
                    redirectUri: string;
                    codeChallenge: string;
                    /**
                     * @default S256
                     * @constant
                     */
                    codeChallengeMethod?: "S256";
                    scope?: string;
                    state?: string;
                    username: string;
                    password: string;
                };
            };
        };
        responses: {
            /** @description Authorization code */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        code: string;
                        state?: string;
                        redirectUri: string;
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @constant */
                    grantType: "authorization_code";
                    code: string;
                    codeVerifier: string;
                    /** Format: uri */
                    redirectUri: string;
                    clientId: string;
                } | {
                    /** @constant */
                    grantType: "refresh_token";
                    refreshToken: string;
                    clientId: string;
                };
            };
        };
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        /** @constant */
                        tokenType: "Bearer";
                        expiresIn: number;
                        refreshToken: string;
                        scope?: string;
                    };
                };
            };
            /** @description Invalid grant */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postOauthRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    refreshToken: string;
                    clientId: string;
                };
            };
        };
        responses: {
            /** @description Tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        accessToken: string;
                        /** @constant */
                        tokenType: "Bearer";
                        expiresIn: number;
                        refreshToken: string;
                        scope?: string;
                    };
                };
            };
            /** @description Invalid refresh token */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteOauthSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getOauthUserinfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        username: string;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        projects: {
                            id: string;
                            title?: string;
                            author?: string;
                            language?: string;
                            createdAt: number;
                            updatedAt: number;
                        }[];
                    };
                };
            };
        };
    };
    postProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
        };
    };
    getProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    title?: string;
                    author?: string;
                    language?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        title?: string;
                        author?: string;
                        language?: string;
                        createdAt: number;
                        updatedAt: number;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    postProjectsByIdSyncByPath: {
        parameters: {
            query?: {
                /** @description The client's current Yjs state vector, encoded as base64url. Omit to receive the full document state. */
                sv?: string;
            };
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Merged Yjs update */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFiles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Files */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        files: {
                            path: string;
                            size: number;
                            contentType: string;
                            updatedAt: number;
                        }[];
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description File contents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Saved */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    deleteProjectsByIdFilesByPath: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    getProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Attachment bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": Uint8Array;
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
    putProjectsByIdAttachmentsBySha256: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                sha256: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/octet-stream": Uint8Array;
            };
        };
        responses: {
            /** @description Stored */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sha256: string;
                        size: number;
                    };
                };
            };
            /** @description Hash mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        error: string;
                        message?: string;
                    };
                };
            };
        };
    };
}
